// <auto-generated />
using IEnumerable_VS_IQueryable_DataSource;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IEnumerable_VS_IQueryable_DataSource.Migrations
{
    [DbContext(typeof(BookContext))]
    partial class BookContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IEnumerable_VS_IQueryable_DataSource.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Robert C. Martin",
                            Price = 550m,
                            Title = "Clean Code"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Jeffrey Richter",
                            Price = 750m,
                            Title = "CLR via C#"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Jon Skeet",
                            Price = 680m,
                            Title = "C# in Depth"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Gang of Four",
                            Price = 900m,
                            Title = "Design Patterns"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Andrew Hunt",
                            Price = 620m,
                            Title = "The Pragmatic Programmer"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Eric Freeman",
                            Price = 500m,
                            Title = "Head First Design Patterns"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Martin Fowler",
                            Price = 800m,
                            Title = "Refactoring"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Eric Evans",
                            Price = 950m,
                            Title = "Domain-Driven Design"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Robert Sedgewick",
                            Price = 720m,
                            Title = "Algorithms"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Thomas H. Cormen",
                            Price = 1100m,
                            Title = "Introduction to Algorithms"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Bill Wagner",
                            Price = 670m,
                            Title = "Effective C#"
                        },
                        new
                        {
                            Id = 12,
                            Author = "Steve McConnell",
                            Price = 870m,
                            Title = "Code Complete"
                        },
                        new
                        {
                            Id = 13,
                            Author = "John Sonmez",
                            Price = 450m,
                            Title = "Soft Skills"
                        },
                        new
                        {
                            Id = 14,
                            Author = "Robert C. Martin",
                            Price = 530m,
                            Title = "The Clean Coder"
                        },
                        new
                        {
                            Id = 15,
                            Author = "Michael Feathers",
                            Price = 990m,
                            Title = "Working Effectively with Legacy Code"
                        },
                        new
                        {
                            Id = 16,
                            Author = "Martin Fowler",
                            Price = 1050m,
                            Title = "Patterns of Enterprise Application Architecture"
                        },
                        new
                        {
                            Id = 17,
                            Author = "Andrew Lock",
                            Price = 780m,
                            Title = "ASP.NET Core in Action"
                        },
                        new
                        {
                            Id = 18,
                            Author = "Joseph Rattz",
                            Price = 640m,
                            Title = "Pro LINQ"
                        },
                        new
                        {
                            Id = 19,
                            Author = "Jon P Smith",
                            Price = 890m,
                            Title = "Entity Framework Core in Action"
                        },
                        new
                        {
                            Id = 20,
                            Author = "Mark Seemann",
                            Price = 710m,
                            Title = "Dependency Injection Principles"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
